num = int(input('Dígite um valor inteiro = '))

print('Sua tabuada até 10 é :')

print(f'{num} * 00 = {num * 0}')
print(f'{num} * 01 = {num * 1}')
print(f'{num} * 02 = {num * 2}')
print(f'{num} * 03 = {num * 3}')
print(f'{num} * 04 = {num * 4}')
print(f'{num} * 05 = {num * 5}')
print(f'{num} * 06 = {num * 6}')
print(f'{num} * 07 = {num * 7}')
print(f'{num} * 08 = {num * 8}')
print(f'{num} * 09 = {num * 9}')
print(f'{num} * 10 = {num * 10}')